import sys
import os

# Safely attempt to load third-party dependencies
try:
    import cairosvg
    from PIL import Image
except ImportError:
    print("\033[91m" + "ERROR: Missing required dependencies." + "\033[0m")
    print("Please run the following command to install them before continuing:")
    print("    pip install cairosvg Pillow")
    sys.exit(1)

def bake_pipeline():
    # Define paths relative to the project root
    svg_input = os.path.join("App", "assets", "logo.svg")
    png_output = os.path.join("App", "assets", "logo.png")
    ico_output = os.path.join("App", "assets", "cyclops_icon.ico")
    header_output = os.path.join("App", "include", "BrandAsset.h")

    # Ensure output directories exist before writing
    os.makedirs(os.path.dirname(png_output), exist_ok=True)
    os.makedirs(os.path.dirname(header_output), exist_ok=True)

    # ---------------------------------------------------------
    # Step 1: SVG to PNG (Rasterization)
    # ---------------------------------------------------------
    if not os.path.exists(svg_input):
        print(f"Error: Input file '{svg_input}' not found in the root directory.")
        sys.exit(1)
    
    print(f"[*] Step 1: Rasterizing {svg_input} to PNG (256x256)...")
    try:
        cairosvg.svg2png(url=svg_input, write_to=png_output, output_width=256, output_height=256)
    except Exception as e:
        print(f"Error during SVG rasterization: {e}")
        sys.exit(1)

    # ---------------------------------------------------------
    # Step 2: PNG to ICO (Windows Icon Generation)
    # ---------------------------------------------------------
    print(f"[*] Step 2: Generating multi-resolution Windows Icon...")
    try:
        img = Image.open(png_output)
        # Windows standard icon sizes for crisp rendering everywhere
        icon_sizes = [(16, 16), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]
        img.save(ico_output, format='ICO', sizes=icon_sizes)
    except Exception as e:
        print(f"Error generating ICO file: {e}")
        sys.exit(1)

    # ---------------------------------------------------------
    # Step 3: PNG to C-Header (Binary Baking)
    # ---------------------------------------------------------
    print(f"[*] Step 3: Baking PNG binary into C++ Header...")
    try:
        with open(png_output, "rb") as f:
            data = f.read()

        # Generate hex-encoded C-array string
        hex_data = [f"0x{byte:02x}" for byte in data]
        
        # Format hex into lines of 16 for readability
        formatted_hex = ""
        for i in range(0, len(hex_data), 16):
            chunk = ", ".join(hex_data[i:i+16])
            formatted_hex += "    " + chunk + ("," if i + 16 < len(hex_data) else "") + "\n"

        header_content = f"""#pragma once

// CyclopsMIPS V1.0 - Professional Asset Branding
// Automatically generated by bake_assets.py - DO NOT EDIT MANUALLY.
// Source: logo.png ({len(data)} bytes)

static const unsigned char logo_png[] = {{
{formatted_hex}}};
"""

        with open(header_output, "w") as f:
            f.write(header_content)
            
    except Exception as e:
        print(f"Error baking C++ header: {e}")
        sys.exit(1)
    
    # ---------------------------------------------------------
    # Success
    # ---------------------------------------------------------
    print("\n[+] SUCCESS: Asset pipeline complete!")
    print(f"    - Generated: {png_output}")
    print(f"    - Generated: {ico_output}")
    print(f"    - Generated: {header_output}")

if __name__ == "__main__":
    bake_pipeline()